"""End-to-end recommendation runs over a real socket (issue #28).

Every case in tests/fixtures/api/recommendation-runs.json builds one synthetic
library under tmp_path with #21's open_database chain, #24's palette operations
and the synthetic contract samples of #9's hybrid fixture, then drives one or
more POST /recommendations requests over a socket served by #27's create_server
with #28's collaborators injected: a scripted #14 transport, #26's own cache or
a stub of it, and the process environment.

Every expectation is hand-written in the fixture file, never read back from the
implementation. No real library path, sample name, content fingerprint,
credential, endpoint or audio byte appears here. The helper shapes are:

    library.kick     key known/unknown, measurement values, status, analysis state
    library.basses   an explicit list, or {count, values} generated by index
    library.palette  which kick and bass the palette selects
    library.after    states applied after the selection: status, role_edits, pruned
    transport        double/interface source, answer, per-dimension overrides
    requests[]       the body sent; "revision" defaults to the stored one
    expect[]         status, code, details, counts, evidence, ids and so on
"""

from __future__ import annotations

from contextlib import closing
from dataclasses import replace
import json
from pathlib import Path
import socket
import threading
import time

import pytest

from backend.analysis import batch
from backend.api.recommendations import (CLIENT_GONE_ATTRIBUTE, RecommendationCollaborators,
                                         RecommendationRequest, run_recommendation)
from backend.contracts import MusicalKey, RecommendationBatch
from backend.intelligence.jev import JevTransportError
from backend.intelligence.jev_double import DEFAULT_MODEL_VERSION, DEFAULT_PROBABILITIES
from backend.library import decision_cache, queue
from backend.library.repository import LibraryRepository
from backend.library.schema import open_database
from backend.palette import ranking
from tests.api_client import start_service


ROOT = Path(__file__).resolve().parents[1]
FIXTURES = ROOT / "tests" / "fixtures" / "api"
CONTRACT_FIXTURES = ROOT / "tests" / "fixtures" / "contracts"
DOCUMENT = ROOT / "_docs" / "recommendation-api.md"

CASES = json.loads((FIXTURES / "recommendation-runs.json").read_text(encoding="utf-8"))["cases"]

#: The known key a case's kick gets when it asks for one, so all five weighted
#: #13 questions are askable.
KNOWN_KEY = MusicalKey(tonic="A", mode="minor", confidence=0.9)

#: The synthetic content identity every fixture row is stored under. The values
#: are index-derived and no real file's fingerprint.
SYNTHETIC_HASHES = {"kick-001": "1" * 64}
for _index in range(1, 101):
    SYNTHETIC_HASHES["bass-%03d" % _index] = "%064x" % (0x1000 + _index)


def _fixture_samples():
    document = RecommendationBatch.from_json(
        (CONTRACT_FIXTURES / "hybrid.json").read_text(encoding="utf-8"))
    return document.samples


#: The fixture's own unknown key, used when a case asks for an unknown one.
UNKNOWN_KEY = _fixture_samples()[0].features.key


def _song_context():
    return RecommendationBatch.from_json(
        (CONTRACT_FIXTURES / "hybrid.json").read_text(encoding="utf-8")).palette.song


def _with_values(sample, values):
    """A copy of one sample with the named measurements replaced.

    A null value becomes the explicit unknown #11 admits: value None, no
    confidence and a stored reason. A known fundamental or tempo replacement is
    given the reliability the contract requires when the fixture carried none.
    """

    measurements = []
    for item in sample.features.measurements:
        if item.name not in values:
            measurements.append(item)
            continue
        value = values[item.name]
        if value is None:
            measurements.append(replace(item, value=None, confidence=None,
                                        unavailable_reason="not_measured"))
            continue
        confidence = item.confidence
        if item.name in ("fundamental", "tempo") and confidence is None:
            confidence = 0.9
        measurements.append(replace(item, value=value, confidence=confidence,
                                    unavailable_reason=None))
    return replace(sample, features=replace(sample.features, measurements=tuple(measurements)))


def _variant(sample, sample_id, *, role=None, values=None, key=None, frames=None):
    """One stored sample of a fixture case, with a synthetic local path."""

    values = dict(values or {})
    if frames == 0:
        # A zero-frame file has no time for a millisecond measurement; the
        # contract's own sample check refuses one that outlives the duration.
        values.update({"transient_position": 0.0, "attack": 0.0, "decay": 0.0})
    changed = _with_values(sample, values)
    if key is not None:
        changed = replace(changed, features=replace(changed.features, key=key))
    if frames is not None:
        changed = replace(changed, audio=replace(
            changed.audio, frame_count=frames,
            duration_ms=0.0 if frames == 0 else frames * 1000 / changed.audio.sample_rate_hz))
    return replace(changed, sample_id=sample_id, role=role or changed.role,
                   audio=replace(changed.audio,
                                 local_path="C:/tera-fixtures/" + sample_id + ".wav"))


def _generated(count, values):
    """One explicit entry per index; "index" becomes -20.0 minus the index."""

    entries = []
    for index in range(1, count + 1):
        entries.append({"id": "bass-%03d" % index,
                        "values": {name: (-20.0 - index if value == "index" else value)
                                   for name, value in (values or {}).items()}})
    return entries


def _other_descriptor():
    """A second analysis descriptor, so one row can hold a stale version."""

    descriptor = dict(batch.analysis_descriptor())
    descriptor["configuration"] = dict(descriptor["configuration"], snapshot="second-version")
    return descriptor


class Built:
    """One synthetic library: where it is, what it holds and what the palette selects."""

    def __init__(self, database, palette_id, revision, kick_id, bass_ids, version):
        self.database = database
        self.palette_id = palette_id
        self.revision = revision
        self.kick_id = kick_id
        self.bass_ids = tuple(bass_ids)
        self.version = version


def build_library(directory, spec):
    """One synthetic library on disk, ready for a recommendation request."""

    spec = spec or {}
    database = str(Path(directory) / "library.sqlite3")
    with closing(open_database(database)) as connection:
        repository = LibraryRepository(connection)
        version = repository.register_analysis_version(batch.analysis_descriptor())
        kick_fixture, bass_fixture = _fixture_samples()[:2]
        kick_spec = spec.get("kick", {})
        kick = replace(_variant(
            kick_fixture, kick_spec.get("id", "kick-001"), role="kick",
            values=kick_spec.get("values"),
            key=KNOWN_KEY if kick_spec.get("key", "known") == "known" else None,
            frames=kick_spec.get("frames")), analysis_version=version)
        _store_kick(repository, connection, kick, version, kick_spec)
        bass_ids = _store_basses(repository, connection, bass_fixture, version,
                                 spec.get("basses"))
        project = repository.create_project("recommendation-fixture", palette_name="Fixture")
        revision = _select(repository, project.palette_id, kick.sample_id, bass_ids,
                           spec.get("palette", {}), spec.get("context", "unset"))
        _apply_states(repository, connection, spec, bass_ids)
    return Built(database, project.palette_id, revision, kick.sample_id, bass_ids, version)


def _store_kick(repository, connection, kick, version, spec):
    """Store the kick row in the analysis state the case asks for."""

    state = spec.get("analysis", "current")
    if state == "current":
        repository.import_sample(kick, content_sha256=SYNTHETIC_HASHES[kick.sample_id],
                                 file_status=spec.get("status", "present"))
        return
    if state == "stale":
        other = repository.register_analysis_version(_other_descriptor())
        repository.import_sample(replace(kick, analysis_version=other),
                                 content_sha256=SYNTHETIC_HASHES[kick.sample_id])
        return
    kick = replace(kick, analysis_version=version)
    # "absent" and the queue states: an indexed row with no analysis at all,
    # exactly as #22 leaves one before #23 stores anything.
    repository.insert_path_record(
        "C:/tera-fixtures/" + kick.sample_id + ".wav", role="kick",
        content_sha256=SYNTHETIC_HASHES[kick.sample_id],
        sample_rate_hz=kick.audio.sample_rate_hz, channels=kick.audio.channels,
        frame_count=kick.audio.frame_count, duration_ms=kick.audio.duration_ms,
        file_status=spec.get("status", "present"), sample_id=kick.sample_id)
    if state in ("pending", "failed"):
        queue.enqueue(connection, version)
        if state == "failed":
            connection.execute(
                "UPDATE job_items SET state = 'failed', error_stage = 'extract', "
                "error_code = 'extractor_failure', error_message = 'synthetic failure' "
                "WHERE sample_id = ?", ("sha256:" + SYNTHETIC_HASHES[kick.sample_id],))


def _store_basses(repository, connection, bass_fixture, version, spec):
    """Store every candidate row of the case and return their ids."""

    entries = _generated(spec.get("count", 0), spec.get("values")) \
        if isinstance(spec, dict) else list(spec or [])
    ids = []
    for entry in entries:
        sample_id = entry["id"]
        key = UNKNOWN_KEY if entry.get("key") == "unknown" else None
        sample = replace(_variant(bass_fixture, sample_id, role=entry.get("role", "bass"),
                                  values=entry.get("values"), key=key),
                         analysis_version=version)
        if entry.get("analysis", "current") == "stale":
            other = repository.register_analysis_version(_other_descriptor())
            repository.import_sample(replace(sample, analysis_version=other),
                                     content_sha256=SYNTHETIC_HASHES[sample_id])
        else:
            repository.import_sample(sample, content_sha256=SYNTHETIC_HASHES[sample_id],
                                     file_status=entry.get("status", "present"))
        ids.append(sample_id)
    return ids


def _select(repository, palette_id, kick_id, bass_ids, palette, context):
    """Select the palette's items and context and return the stored revision."""

    revision = 0
    if palette.get("kick", True):
        revision = repository.set_palette_item(palette_id, "kick", kick_id,
                                               expected_revision=revision).revision
    bass = palette.get("bass")
    if bass:
        revision = repository.set_palette_item(palette_id, "bass", bass,
                                               expected_revision=revision).revision
    if context == "known":
        revision = repository.set_palette_context(palette_id, _song_context(),
                                                  expected_revision=revision).revision
    return revision


def _apply_states(repository, connection, spec, bass_ids):
    """Apply the states a case needs after the palette selection exists."""

    after = spec.get("after", {})
    for sample_id, status in (after.get("status") or {}).items():
        repository.mark_file_status(sample_id, status)
    for sample_id in after.get("role_edits") or ():
        connection.execute("UPDATE samples SET role = 'bass' WHERE sample_id = ?", (sample_id,))
    for sample_id in after.get("pruned") or ():
        # #71 pruning removes the sample row; the palette item deliberately has
        # no foreign key, so the selection survives and the kick reads as absent.
        repository.delete_sample(sample_id)


class ScriptedTransport:
    """A test-local #14 transport: deterministic answers and an ordered call log.

    Every response is built from the payload the adapter sent, so it always
    echoes the asked question id, dimension and prompt version. A per-dimension
    override lets one case answer one dimension differently, an optional gate
    blocks a send until the test releases it, and an optional hook runs on every
    send.
    """

    def __init__(self, spec, *, on_send=None):
        self.source = spec.get("source", "double")
        self.interface_name = spec.get("interface_name", "jev-contract-double")
        self.spec = spec
        self.on_send = on_send
        self.gate = None
        self.blocked = threading.Event()
        self.release = threading.Event()
        self.calls = []

    def answer_for(self, dimension):
        """The merged answer spec of one dimension: case defaults plus override."""

        answer = {name: value for name, value in self.spec.items() if name != "overrides"}
        answer.update((self.spec.get("overrides") or {}).get(dimension) or {})
        return answer

    def send(self, payload_json, *, timeout_s):
        payload = json.loads(payload_json)
        dimension = payload["dimension"]
        self.calls.append(payload)
        if self.on_send is not None:
            self.on_send(len(self.calls))
        if self.gate is not None and self.gate(len(self.calls)):
            self.blocked.set()
            self.release.wait(timeout=30)
            self.blocked.clear()
        answer = self.answer_for(dimension)
        kind = answer.get("answer", "judgment")
        if kind == "timeout":
            raise JevTransportError("timeout", "The scripted transport timed out.")
        if kind == "service_error":
            raise JevTransportError("service_error", "The scripted transport failed.")
        if kind == "text":
            return "this is not a JSON response object"
        model_version = answer.get("model_version", DEFAULT_MODEL_VERSION)
        if kind == "abstain":
            body = {"question_id": payload["question_id"], "dimension": dimension, "label": None,
                    "probabilities": None, "confidence": None, "model_version": model_version,
                    "prompt_version": payload["prompt_version"],
                    "unavailable_reason": "model_abstained"}
            return json.dumps(body, allow_nan=False, sort_keys=True)
        probabilities = answer.get("probabilities", list(DEFAULT_PROBABILITIES))
        # 0.8 is the #11/#12 reliability threshold: a scripted judgment at it is
        # not uncertain, and a case that wants an uncertain result answers lower.
        confidence = answer.get("confidence", 0.8)
        labels = ("very-poor", "poor", "neutral", "good", "excellent")
        body = {"question_id": payload["question_id"], "dimension": dimension,
                "label": labels[probabilities.index(max(probabilities))],
                "probabilities": [{"label": name, "probability": value}
                                  for name, value in zip(labels, probabilities)],
                "confidence": confidence, "model_version": model_version,
                "prompt_version": payload["prompt_version"], "unavailable_reason": None}
        return json.dumps(body, allow_nan=False, sort_keys=True)


def collaborators_for(case, *, built=None, on_send=None, gate=None):
    """The collaborators and scripted transport one case asks for."""

    spec = case.get("transport")
    transport = None
    if spec is not None and spec.get("kind") != "none":
        transport = ScriptedTransport(spec, on_send=on_send)
        if gate is not None:
            transport.gate = gate
    return RecommendationCollaborators(transport=transport, environ=case.get("environ", {}),
                                       cache=case.get("cache"), monotonic=case.get("monotonic")), \
        transport


def _request_body(built, request):
    body = dict(request)
    body["palette_id"] = built.palette_id
    revision = body.pop("revision", "current")
    if revision == "current":
        revision = built.revision
    elif revision == "stale":
        revision = built.revision - 1
    body["revision"] = revision
    return body


def check_reply(reply, expect, *, built, previous):
    """Assert one response against one hand-written expectation."""

    assert reply.status == expect["status"], reply.raw
    if expect["status"] != 200:
        assert reply.body["error"]["code"] == expect["code"], reply.raw
        assert reply.body["error"]["details"] == _details(expect.get("details", {}), built), \
            reply.raw
        return None
    assert set(reply.body) == {"api_schema", "recommendation", "run"}, reply.raw
    assert reply.body["api_schema"] == "1.0"
    recommendation, run = reply.body["recommendation"], reply.body["run"]
    if "mode" in expect:
        assert recommendation["mode"] == expect["mode"], reply.raw
    if "jev_status" in expect:
        assert run["ranking"]["jev_status"] == expect["jev_status"], reply.raw
    if "counts" in expect:
        assert run["counts"] == expect["counts"], reply.raw
    if "evidence" in expect:
        assert run["evidence"] == expect["evidence"], reply.raw
    if "exclusions" in expect:
        assert run["exclusions"] == expect["exclusions"], reply.raw
    if "limit_reason" in expect:
        assert run["retrieval"]["limit_reason"] == expect["limit_reason"], reply.raw
    if "model_versions" in expect:
        assert run["jev"]["model_versions"] == expect["model_versions"], reply.raw
    if "shortlist_size_requested" in expect:
        assert run["retrieval"]["shortlist_size_requested"] == expect["shortlist_size_requested"]
    if "result_ids" in expect:
        assert [record["candidate_id"] for record in recommendation["results"]] == \
            expect["result_ids"], reply.raw
    if "alternative_ids" in expect:
        assert recommendation["alternatives"] == expect["alternative_ids"], reply.raw
    # Every alternative is inside the returned results, every evidence count is
    # exactly one of the four sources per weighted dimension of a scored
    # candidate, and no case returns 500.
    assert set(recommendation["alternatives"]) <= {record["candidate_id"]
                                                   for record in recommendation["results"]}
    evidence = run["evidence"]
    assert evidence["interface"] + evidence["double"] + evidence["unavailable"] \
        + evidence["cache"] == 5 * run["counts"]["scored"]
    assert run["counts"]["returned"] == min(run["counts"]["requested"], run["counts"]["scored"])
    assert run["counts"]["shortlisted"] == run["retrieval"]["shortlist_size_returned"]
    if "sample_ids" in expect:
        ids = [sample["sample_id"] for sample in recommendation["samples"]]
        assert sorted(ids) == sorted(expect["sample_ids"]), reply.raw
        assert len(ids) == len(set(ids)), reply.raw
    if "similarity_null" in expect:
        nulls = {record["candidate_id"] for record in recommendation["results"]
                 if record["similarity"] is None}
        assert nulls == set(expect["similarity_null"]), reply.raw
    if "unknown_measurement" in expect:
        _check_unknown(recommendation, expect["unknown_measurement"])
    if "same_recommendation_as" in expect:
        assert recommendation == previous[expect["same_recommendation_as"]]["recommendation"]
    if "same_run_id_as" in expect:
        assert run["run_id"] == previous[expect["same_run_id_as"]]["run"]["run_id"]
    if "different_run_id_from" in expect:
        assert run["run_id"] != previous[expect["different_run_id_from"]]["run"]["run_id"]
    if expect.get("dsp_baseline"):
        _check_dsp_baseline(recommendation, built)
    return reply.body


def _details(details, built):
    """One expectation's details, with the request's own palette id substituted."""

    return {name: (built.palette_id if value == "<palette>" else value)
            for name, value in details.items()}


def _check_unknown(recommendation, spec):
    """One unknown measurement keeps its null and its reason and claims no confidence."""

    sample = next(item for item in recommendation["samples"]
                  if item["sample_id"] == spec["sample_id"])
    measurement = next(item for item in sample["features"]["measurements"]
                       if item["name"] == spec["name"])
    assert measurement["value"] is None
    assert measurement["unavailable_reason"] == spec["reason"]
    assert measurement["confidence"] is None


def _check_dsp_baseline(recommendation, built):
    """The DSP-only fallback equals #12's own result for the same inputs."""

    with closing(open_database(built.database)) as connection:
        repository = LibraryRepository(connection)
        kick = repository.get_sample(built.kick_id, built.version).sample
        rows = repository.list_retrieval_rows(built.version, sample_ids=built.bass_ids)
        candidates = tuple(row.sample for row in rows if row.sample is not None)
    baseline = ranking.rank_candidates(kick, candidates, policy=ranking.RankingPolicy())
    for projected, record in zip(recommendation["results"], baseline.ranked):
        assert projected["candidate_id"] == record.candidate_id
        assert (projected["compatibility"], projected["confidence"]) == \
            (record.compatibility, record.confidence)
        # The fallback copies #12's reasons and warnings unchanged and in order.
        assert projected["reasons"] == list(record.reasons)
        assert projected["warnings"] == list(record.warnings)
        assert projected["dsp_dimensions"] == [entry.to_dict() for entry in record.dsp_dimensions]
        assert not projected["jev_judgments"]


def _hook(case, built):
    """The per-send hook one case scripts; the palette bump is the only one."""

    if case.get("on_send") != "bump_palette_revision":
        return None

    def hook(count):
        if count != 1:
            return
        with closing(open_database(built.database)) as connection:
            # Re-selecting the same kick is a documented no-op, so the change is a
            # different bass: the revision and the content hash both move.
            LibraryRepository(connection).set_palette_item(
                built.palette_id, "bass", built.bass_ids[1], expected_revision=built.revision)

    return hook


@pytest.mark.parametrize("case", CASES, ids=[case["name"] for case in CASES])
def test_the_run_cases_hold(tmp_path, case):
    built = build_library(tmp_path, case.get("library"))
    collaborators, transport = collaborators_for(case, built=built, on_send=_hook(case, built))
    running = start_service(built.database, recommendations=collaborators)
    previous = []
    try:
        for request, expect in zip(case["requests"], case["expect"]):
            before = 0 if transport is None else len(transport.calls)
            reply = running.client.post("/recommendations", _request_body(built, request))
            if transport is not None and "sends" in expect:
                assert len(transport.calls) - before == expect["sends"], reply.raw
            answer = check_reply(reply, expect, built=built, previous=previous)
            previous.append(answer)
        if "cache_entries" in case:
            with closing(open_database(built.database)) as connection:
                assert decision_cache.cache_stats(connection).entries == case["cache_entries"]
    finally:
        running.stop()


# ---------------------------------------------------------------------------
# the budget, the abort and the version changes
# ---------------------------------------------------------------------------


class FakeClock:
    """One thread-safe monotonic clock a test can advance."""

    def __init__(self, start=1000.0):
        self._value = start
        self._lock = threading.Lock()

    def __call__(self):
        with self._lock:
            return self._value

    def advance(self, seconds):
        with self._lock:
            self._value += seconds


def test_the_budget_returns_honest_partial_evidence_within_the_bound(tmp_path):
    case = _rule_case("a cache hit on the second request")
    clock = FakeClock()
    built_case = {"library": case["library"], "transport": case["transport"]}
    built = build_library(tmp_path, built_case["library"])
    collaborators, transport = collaborators_for(dict(built_case, monotonic=clock),
                                                 built=built, gate=lambda count: count == 1)
    collaborators = replace(collaborators, monotonic=clock)
    running = start_service(built.database, recommendations=collaborators)
    try:
        started = time.monotonic()
        outcome = {}

        def call():
            outcome["reply"] = running.client.post(
                "/recommendations", _request_body(built, case["requests"][0]))

        thread = threading.Thread(target=call, daemon=True)
        thread.start()
        assert transport is not None
        assert transport.blocked.wait(timeout=30), "the transport never blocked"
        health_started = time.monotonic()
        health = running.client.get("/health")
        assert health.status == 200
        assert time.monotonic() - health_started < 1
        clock.advance(30.0)
        transport.release.set()
        thread.join(30)
        assert not thread.is_alive()
        assert time.monotonic() - started < 27.0
        reply = outcome["reply"]
        assert reply.status == 200
        run = reply.body["run"]
        assert run["evidence"]["cache"] == 0
        assert run["evidence"]["interface"] == 0
        assert run["evidence"]["unavailable"] > 0
        assert run["evidence"]["unavailable"] + run["evidence"]["double"] == \
            5 * run["counts"]["scored"]
        assert running.client.get("/health").status == 200
        follow_up = running.client.post("/recommendations",
                                        _request_body(built, case["requests"][0]))
        assert follow_up.status == 200
    finally:
        running.stop()


def test_an_aborted_request_stops_at_the_stage_boundary_and_publishes_nothing(tmp_path):
    case = _rule_case("a cache hit on the second request")
    built_case = {"library": case["library"], "transport": case["transport"]}
    built = build_library(tmp_path, built_case["library"])
    collaborators, transport = collaborators_for(built_case, built=built,
                                                 gate=lambda count: count == 1)
    running = start_service(built.database, recommendations=collaborators)
    try:
        before = _palette_state(built.database, built.palette_id)
        opened = _send_raw(running.port, "/recommendations",
                           _request_body(built, case["requests"][0]))
        assert transport.blocked.wait(timeout=30), "the transport never blocked"
        first_batch = len(transport.calls)
        opened.close()
        # The requesting client is gone and the application publishes the
        # documented signal: #27's route context carries no connection, so this
        # is the one observable form of "the request socket has no client".
        running.app.__dict__[CLIENT_GONE_ATTRIBUTE] = True
        transport.release.set()
        deadline = time.monotonic() + 30
        while len(transport.calls) == first_batch and time.monotonic() < deadline:
            time.sleep(0.02)
        running.app.__dict__[CLIENT_GONE_ATTRIBUTE] = False
        assert len(transport.calls) == first_batch
        assert _palette_state(built.database, built.palette_id) == before
        assert running.client.get("/health").status == 200
        follow_up = running.client.post("/recommendations",
                                        _request_body(built, case["requests"][0]))
        assert follow_up.status == 200
    finally:
        running.stop()


def _send_raw(port, path, body):
    """One raw request whose socket the caller can close mid-flight."""

    opened = socket.create_connection(("127.0.0.1", port), timeout=30)
    payload = json.dumps(body).encode("utf-8")
    head = ("POST %s HTTP/1.1\r\nHost: 127.0.0.1:%d\r\nContent-Type: application/json\r\n"
            "Content-Length: %d\r\n\r\n" % (path, port, len(payload))).encode("ascii")
    opened.sendall(head + payload)
    return opened


def _palette_state(database, palette_id):
    """The palette's revision and content hash, as the criterion compares them."""

    from backend.palette.model import palette_hash

    with closing(open_database(database)) as connection:
        record = LibraryRepository(connection).load_palette(palette_id)
    return record.revision, palette_hash(record)


def _rule_case(name):
    """One fixture case, so a test and the fixture describe the same library."""

    for case in CASES:
        if case["name"] == name:
            return case
    raise AssertionError(name)


#: The five version constants the criterion replaces in turn and the run-block
#: path each one is reported at.
VERSION_BUMPS = (
    ("backend.palette.ranking", "HYBRID_RANKING_VERSION", ("ranking", "ranking_version"), True),
    # The weight table id a result carries is the table it was built with, so a
    # replaced constant moves run_id and the report keeps the result's own value.
    ("backend.palette.ranking", "HYBRID_WEIGHT_TABLE_ID", ("ranking", "weight_table_id"), False),
    ("backend.palette.retrieval", "RETRIEVAL_POLICY_VERSION",
     ("retrieval", "policy_version"), True),
    ("backend.intelligence.questions", "PROMPT_VERSION", ("jev", "prompt_version"), True),
    ("backend.intelligence.jev", "ADAPTER_VERSION", ("jev", "adapter_version"), True),
)


@pytest.mark.parametrize("module_name,constant,path,reported", VERSION_BUMPS,
                         ids=[bump[1] for bump in VERSION_BUMPS])
def test_a_version_bump_is_reported_and_changes_the_run_id(tmp_path, monkeypatch, module_name,
                                                           constant, path, reported):
    import importlib

    module = importlib.import_module(module_name)
    case = _rule_case("a fully judged 12-candidate run")
    built = build_library(tmp_path, case["library"])
    collaborators, transport = collaborators_for(case, built=built)
    running = start_service(built.database, recommendations=collaborators)
    try:
        first = running.client.post("/recommendations", _request_body(built, case["requests"][0]))
        assert first.status == 200
        monkeypatch.setattr(module, constant, getattr(module, constant) + "-bumped")
        second = running.client.post("/recommendations", _request_body(built, case["requests"][0]))
        assert second.status == 200
        assert second.body["run"]["run_id"] != first.body["run"]["run_id"]
        if reported:
            assert second.body["run"][path[0]][path[1]] != first.body["run"][path[0]][path[1]]
        else:
            assert second.body["run"][path[0]][path[1]] == \
                ranking.DEFAULT_HYBRID_WEIGHT_TABLE.identifier
        assert second.body["recommendation"]["ranking_version"] == \
            second.body["run"]["ranking"]["ranking_version"]
    finally:
        running.stop()


def test_an_unknown_band_takes_the_unavailable_path(tmp_path):
    """A candidate #11 admits with an unknown band keeps its nulls and reasons.

    The criterion asks a candidate admitted with unknown F0, key, loudness,
    bands or envelope to keep its nulls and reasons and still rank. #12's
    frequency evidence now returns its own unavailable score for an incomplete
    band set instead of summing a missing value; #12 owns that semantics and
    tests/test_dsp_baseline.py carries the focused regression rows.
    """

    built = build_library(tmp_path, {"kick": {"key": "known"}, "basses": [],
                                     "palette": {"kick": True, "bass": None}})
    with closing(open_database(built.database)) as connection:
        repository = LibraryRepository(connection)
        kick = repository.get_sample(built.kick_id, built.version).sample
        bands = {name: None for name in ("band_sub", "band_bass", "band_low_mid", "band_mid",
                                         "band_high_mid", "band_high")}
        candidate = replace(_variant(built_bass(), "bass-001", values=bands),
                            analysis_version=built.version)
    result = ranking.rank_candidates(kick, (candidate,), policy=ranking.RankingPolicy())
    # The candidate is neither dropped nor invented: its frequency dimension is
    # unavailable, its other dimensions still score it, and the measurement keeps
    # its null and its reason.
    assert len(result.ranked) == 1 and result.unscored == ()
    entry = next(entry for entry in result.ranked[0].dsp_dimensions
                 if entry.dimension == "frequency")
    assert entry.compatibility is None
    assert entry.unavailable_reason == "candidate_band_unknown"
    assert result.ranked[0].compatibility is not None
    measurement = next(item for item in candidate.features.measurements
                       if item.name == "band_sub")
    assert measurement.value is None and measurement.unavailable_reason


def built_bass():
    """The fixture's bass sample, for tests that need one contract record."""

    return _fixture_samples()[1]


def test_the_reported_versions_are_the_ranking_results_own(tmp_path):
    case = _rule_case("a fully degraded run with credentials absent")
    built = build_library(tmp_path, case["library"])
    collaborators, transport = collaborators_for(case, built=built)
    running = start_service(built.database, recommendations=collaborators)
    try:
        reply = running.client.post("/recommendations", _request_body(built, case["requests"][0]))
        assert reply.status == 200
        run = reply.body["run"]
        assert run["ranking"]["ranking_version"] == ranking.RANKING_VERSION
        assert run["ranking"]["weight_table_id"] == ranking.DEFAULT_WEIGHT_TABLE_ID
        assert reply.body["recommendation"]["ranking_version"] == run["ranking"]["ranking_version"]
    finally:
        running.stop()


def test_the_similarity_and_reasons_are_the_landed_values_verbatim(tmp_path):
    """#25's similarity pair and #12's reasons reach the wire unchanged."""

    from backend.library.retrieval import retrieve_shortlist
    from backend.palette.retrieval import RetrievalPolicy

    case = _rule_case("a fully judged 12-candidate run")
    built = build_library(tmp_path, case["library"])
    collaborators, transport = collaborators_for(case, built=built)
    running = start_service(built.database, recommendations=collaborators)
    try:
        reply = running.client.post("/recommendations", _request_body(built, case["requests"][0]))
        assert reply.status == 200, reply.raw
        with closing(open_database(built.database)) as connection:
            stored = retrieve_shortlist(connection, built.kick_id, policy=RetrievalPolicy())
            rows = LibraryRepository(connection).list_retrieval_rows(
                built.version, sample_ids=built.bass_ids)
            kick = LibraryRepository(connection).get_sample(built.kick_id, built.version).sample
            candidates = tuple(row.sample for row in rows if row.sample is not None)
        ranked_by_id = {record.sample_id: record for record in stored.result.ranked}
        baseline = ranking.rank_candidates(kick, candidates, policy=ranking.RankingPolicy())
        baseline_by_id = {record.candidate_id: record for record in baseline.ranked}
        for projected in reply.body["recommendation"]["results"]:
            candidate_id = projected["candidate_id"]
            retrieved = ranked_by_id[candidate_id]
            assert projected["similarity"] == retrieved.similarity
            assert projected["similarity_unavailable_reason"] == \
                retrieved.similarity_unavailable_reason
            # #15 keeps #12's reasons unchanged and starts its warnings with
            # #12's own, then appends its own documented codes.
            original = baseline_by_id[candidate_id]
            assert projected["reasons"] == list(original.reasons)
            assert projected["warnings"][:len(original.warnings)] == list(original.warnings)
            assert any(warning.startswith(("dimension_disagreement", "low_coverage",
                                           "low_jev_confidence", "candidate_no_jev_evidence",
                                           "jev_evidence_unavailable", "unweighted_dimension"))
                       for warning in projected["warnings"])
    finally:
        running.stop()


def test_a_permuted_candidate_population_leaves_the_block_identical(tmp_path, monkeypatch):
    """The block is a function of content, not of the read order."""

    case = _rule_case("a fully judged 12-candidate run")
    built = build_library(tmp_path, case["library"])
    collaborators, transport = collaborators_for(case, built=built)
    running = start_service(built.database, recommendations=collaborators)
    try:
        first = running.client.post("/recommendations", _request_body(built, case["requests"][0]))
        assert first.status == 200, first.raw
        original = LibraryRepository.list_retrieval_rows

        def reversed_rows(self, analysis_version, *, sample_ids=None, roles=None):
            rows = original(self, analysis_version, sample_ids=sample_ids, roles=roles)
            return tuple(reversed(rows)) if roles is not None else rows

        monkeypatch.setattr(LibraryRepository, "list_retrieval_rows", reversed_rows)
        second = running.client.post("/recommendations", _request_body(built, case["requests"][0]))
        assert second.status == 200, second.raw
        assert second.body["recommendation"] == first.body["recommendation"]
        assert second.body["run"]["run_id"] == first.body["run"]["run_id"]
    finally:
        running.stop()


def test_the_recommendation_block_is_deterministic_for_the_same_evidence(tmp_path):
    case = _rule_case("a fully judged 12-candidate run")
    built = build_library(tmp_path, case["library"])
    body = _request_body(built, case["requests"][0])
    collaborators, transport = collaborators_for(case, built=built)
    running = start_service(built.database, recommendations=collaborators)
    try:
        first = running.client.post("/recommendations", body)
        second = running.client.post("/recommendations", body)
        assert first.status == second.status == 200
        assert first.body["recommendation"] == second.body["recommendation"]
        assert first.body["run"]["run_id"] == second.body["run"]["run_id"]
        assert first.body["run"]["evidence"] != second.body["run"]["evidence"]
    finally:
        running.stop()


def test_the_library_read_bound_does_not_grow_with_the_shortlist(tmp_path, monkeypatch):
    """The reads one successful run executes are the same at 12 and at 100.

    The cache is stubbed to perform no SQL, so the trace holds only the landed
    library reads: the palette before the run and after ranking, the kick row,
    #25's own kick and population reads, one keyed shortlist read and the cache's
    model-version pin.
    """

    # #26's own reads are excluded from this bound, exactly as the criterion
    # states: the pin lookup and the pin write-back are the cache's bookkeeping.
    monkeypatch.setattr(decision_cache, "pinned_model_version", lambda *args, **kwargs: None)
    monkeypatch.setattr(decision_cache, "record_model_version", lambda *args, **kwargs: None)
    counts = {}
    case = _rule_case("a fully judged 12-candidate run")
    for size in (12, 100):
        directory = tmp_path / ("size-%d" % size)
        directory.mkdir()
        built = build_library(directory, {"kick": {"key": "known"},
                                          "basses": {"count": size,
                                                     "values": {"loudness": "index"}},
                                          "palette": {"kick": True, "bass": "bass-001"}})
        request = RecommendationRequest(palette_id=built.palette_id, revision=built.revision,
                                        limit=10)
        collaborators = RecommendationCollaborators(
            transport=ScriptedTransport(case["transport"]), environ={}, cache=_NoSqlCache())
        with closing(open_database(built.database)) as connection:
            trace = _Trace()
            connection.set_trace_callback(trace.record)
            try:
                result = run_recommendation(connection, request, collaborators=collaborators,
                                            cancelled=lambda: False)
            finally:
                connection.set_trace_callback(None)
            assert result.run.counts.scored == size
            assert result.run.evidence.double == 5 * size
            counts[size] = trace.reads()
    assert counts[12] == counts[100]
    # The whole run's constant read set: this route's palette read before the run
    # and after ranking (seven statements each, #24's record resolves every item),
    # its kick row (two), #25's own kick and population reads (eight) and the one
    # keyed shortlist read (two).
    assert counts[100] == 26


class _Trace:
    """Every read the connection executed during one request."""

    def __init__(self):
        self.statements = []

    def record(self, statement):
        self.statements.append(statement)

    def reads(self):
        return sum(1 for statement in self.statements
                   if statement.lstrip().upper().startswith("SELECT"))


class _NoSqlCache:
    """A #26 handle stubbed to perform no SQL: every lookup is a miss."""

    def lookup(self, connection, key, *, question):
        return decision_cache.CacheLookup(status="miss", reason="absent", judgment=None,
                                          decision=None, stale_found=False,
                                          entry_created_at=None)

    def store(self, connection, key, *, outcome):
        return decision_cache.StoreResult(stored=False, created_at=None, pruned=0)
